site_name: Vector Search | Weekly Topics & News
site_description: an example blog set up following the tutorial
site_url: http://www.vectorsearch.tech

theme:
  name: material
  icon:
    logo: material/rocket-launch-outline
  palette:
      scheme: slate
      primary: black
      accent: red
  font:
    text: Samurai
    code: Roboto Mono
  features:
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

repo_url: https://github.com/davidmyriel/blog
repo_name: davidmyriel/blog

plugins:
  - search
  - blog: 
      blog_dir: . 
      post_url_format: "{slug}"
extra:
  generator: false
  analytics:
    provider: google
    property: G-VT22GS7WB4
  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/davidmyriel
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/davidmyriel/

copyright: Copyright &copy; 2025 David Myriel | Opinions expressed are solely my own and do not express the views or opinions of my employer.