site_name: Vector Search | Weekly Topics
theme:
  name: material

  Plugins:
    - Blog:
        authors_profiles: true
  
  nav:
  - index.md
  - Blog:
    - blog/index.md
        
  markdown_extensions:
    - attr_list 

  palette:
      scheme: slate
      primary: black
      accent: indigo

  font:
    text: Roboto
    code: Roboto Mono

  repo_url: https://github.com/davidmyriel/blog
  repo_name: davidmyriel/blog

  icon:
    repo: fontawesome/brands/git-alt

